SUBDIRS=syslog_jni


all:
	@for d in $(SUBDIRS); do make -C $$d $@ ; done
clean:
	@for d in $(SUBDIRS); do make -C $$d $@ ; done
install:
	@for d in $(SUBDIRS); do make -C $$d $@ ; done
debug:
	@for d in $(SUBDIRS); do make -C $$d $@ ; done
